export const MAX_COLLECTION_IMG_SIZE = 104857600;
export const MAX_COLLECTION_IMG_SIZE_TEXT = "100MB";
export const FREE_USER_MAX_CARD_NUM = 100;
export const FREE_USER_MAX_COLLECTION_NUM = 10;
export const FREE_USER_CODE = 4780;
